### ISSUE TITLE
SceneAccess SSL support gone

### ISSUE THREAD

**Issue by Eihrister** [SiCKRAGETV/sickrage-issues#1516]
Hi,

From the log:

Unable to connect to SceneAccess provider: error [Errno 1] _ssl.c:504: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error

I don't know where in the Python scripts I can define SSL options, but this needs an exception somewhere in order to work again. Could you please let me know how/where it connects and with what module, or perhaps patch it?

The SCC website works just fine, and curl on the server directly also works just fine.
However, wget also can not connect, and throws a "GnuTLS: A TLS fatal alert has been received.".

If need be, I can just create a new container and not update all the SSL libraries on that container and just leave that for SickRage to download its stuff, bu I prefer to have everything up-to-date :)

Eihrister

p.s.: Running on Debian GNU/Linux 7.8 Wheezy (SickRage + Plex container).

**Comment by Eihrister** [comment]
FYI: Made a container with Ubuntu 15.04 Vivid Vervet, moved my SR install, and everything works fine there. It also seems to work fine on Debian GNU/Linux 8.0 (Jessie), but not with an up-to-date Debian 7 install as said above.

**Comment by jatwigg** [comment]
I have exactly the same issue on ubuntu 14.10

**Comment by miigotu** [comment]
Next time pls search issues. This has been reported literally like 100 times, and fixed. [SSL Errors](https://github.com/SiCKRAGETV/sickrage-issues/wiki/SSL-Errors)

It works on Vivid because vivid uses Python 2.7.9 afaik.
