### ISSUE TITLE
nzbToMedia call causes redirect to homepage

### ISSUE THREAD

**Issue by DirtyDutch** [SiCKRAGETV/sickrage-issues#279]
When calling the following URL SickRage redirects to the homepage and won't process the file:

http://localhost:8081/sickbeard//home/postprocess/processEpisode with params: {'nzbName': 'example', 'quiet': 1, 'failed': 0, 'process_method': '1', 'dir': 'example'}

Is it a bug in nzbtomedia, or has there something changed in Sickrage? Always worked before, seems that the processEpisode method handles it a bit different and not understaning it anymore..

Branch: master
Hash: 33e95870e0c1b241c93f541d4ee27ed6ba3bfcb8

Getting also the following error:
```
AAAttributeError: 'WebRoot' object has no attribute 'home/postprocess/processEpisode'
AA    method = getattr(self, route)
AA  File "C:\SickBeard-TVRage\sickbeard\webserve.py", line 214, in get
```

**Comment by heymoe** [comment]
This sounds like the issue I was having after upgrading to v4.x.x. SickRage would trigger a download via NZBGet but using nzbToMedia to trigger SickRage to process the download would fail and looking at the debug log it looked like nzbToMedia received the SickRage login page. 

It turns out the version of nzbToMedia I was running was old. After upgrading to the latest version, everything started to work again.
